export const REQUEST_POSTS = "REQUEST_POSTS";
export const REQUEST_POSTS_SUCCESS = "REQUEST_POSTS_SUCCESS";
export const REQUEST_POSTS_ERROR = "REQUEST_POSTS_ERROR";

export const REQUEST_USER_CONVERSATIONS = "REQUEST_USER_CONVERSATIONS";
export const REQUEST_USER_CONVERSATIONS_ERROR = "REQUEST_USER_CONVERSATIONS_ERROR";
export const REQUEST_USER_CONVERSATIONS_SUCCESS = "REQUEST_USER_CONVERSATIONS_SUCCESS";

export const TOGGLE_CONVERSATIONS = "TOGGLE_CONVERSATIONS";
export const TOGGLE_POST_COMMENTS = "TOGGLE_POST_COMMENTS";
export const TOGGLE_COMMENT_REPLIES = "TOGGLE_COMMENT_REPLIES";
export const GET_POST_COMMENTS_SUCCESS = "GET_POST_COMMENTS_SUCCESS";
export const GET_POST_COMMENTS_ERROR = "GET_POST_COMMENTS_ERROR";

export const GET_COMMENT_REPLIES_SUCCESS = "GET_COMMENT_REPLIES_SUCCESS";
export const GET_COMMENT_REPLIES_ERROR = "GET_COMMENT_REPLIES_ERROR";

export const LIKE_SUCCESS = "LIKE_SUCCESS";
export const LIKE_ERROR = "LIKE_ERROR";

export const SHOW_NEW_COMMENT_FORM = "SHOW_NEW_COMMENT_FORM";
export const NEW_COMMENT_SUCCESS = "NEW_COMMENT_SUCCESS";
export const NEW_COMMENT_ERROR = "NEW_COMMENT_ERROR";
export const SET_NEW_COMMENT_CONTENT = "SET_NEW_COMMENT_CONTENT";

export const COMMENT_UPDATED = "COMMENT_UPDATED";
