export const REQUEST_DASHBOARD = "REQUEST_DASHBOARD";
export const REQUEST_DASHBOARD_SUCCESS = "REQUEST_DASHBOARD_SUCCESS";
export const REQUEST_DASHBOARD_ERROR = "REQUEST_DASHBOARD_ERROR";

export const REQUEST_USER_CONVERSATIONS = "REQUEST_USER_CONVERSATIONS";
export const REQUEST_USER_CONVERSATIONS_ERROR = "REQUEST_USER_CONVERSATIONS_ERROR";
export const REQUEST_USER_CONVERSATIONS_SUCCESS = "REQUEST_USER_CONVERSATIONS_SUCCESS";

export const TOGGLE_CONVERSATIONS = "TOGGLE_CONVERSATIONS";
export const TOGGLE_POST_COMMENTS = "TOGGLE_POST_COMMENTS";

export const GET_POST_COMMENTS_SUCCESS = "GET_POST_COMMENTS_SUCCESS";
export const GET_POST_COMMENTS_ERROR = "GET_POST_COMMENTS_ERROR";
